Models/ErrorViewModel.cs
namespace Areas_2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Areas/Collage/Controllers/CollageController.cs
using Microsoft.AspNetCore.Mvc;

namespace Areas_2.Areas.Collage.Controllers
{
    [Area("Collage")]
    [Route("Collage/[controller]/[action]")]
    public class CollageController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult collage_detail()
        {
            return View();
        }
    }
}

Controllers/CountryController.cs
using Microsoft.AspNetCore.Mvc;

namespace Areas_2.Controllers
{
    public class CountryController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using Areas_2.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Areas_2.Controllers
{
    //[Area("Collage")]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Hello()
        {
            return View();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Areas/Collage/Views/Collage/collage_detail.cshtml
<html>
    <head></head>
    <body>
        <h1>Hello This Is Area Of Collage Detail</h1>
    </body>
</html>

Views/Country/Index.cshtml
<h1>Helllo From Country</h1>

Views/Home/Hello.cshtml
<h1>THis Is Hellllo</h1>

Views/Home/Index.cshtml
<h1>This Is Home</h1>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Areas_2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Areas_2.styles.css" asp-append-version="true" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" asp-action="Index" asp-controller="">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" asp-action="Hello" asp-controller="Home">Helllo</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" asp-action="" asp-controller="Country">Country</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" asp-action="collage_detail" asp-controller="Collage" asp-area="Collage">Collage</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
        <div> @RenderBody()</div>
</body>
</html>